# Generated by Django 3.2.25 on 2024-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadobotao',
            old_name='estado',
            new_name='estado2',
        ),
        migrations.AddField(
            model_name='estadobotao',
            name='estado1',
            field=models.BooleanField(default=False),
        ),
    ]
