# Generated by Django 3.2.25 on 2024-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20240728_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadobotao',
            name='estado1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estadobotao',
            name='estado2',
            field=models.CharField(max_length=20),
        ),
    ]
