# Generated by Django 3.2.25 on 2024-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20240728_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadobotao',
            name='estado1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estadobotao',
            name='estado2',
            field=models.BooleanField(default=False),
        ),
    ]
